# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 12:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='Создано')),
                ('changed', models.DateTimeField(verbose_name='Изменено')),
                ('fio', models.TextField(verbose_name='Фамилия, имя, отчество должника')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Долг')),
                ('passport', models.TextField(verbose_name='Номер пасспорта')),
                ('status', models.TextField(choices=[('new', 'новое'), ('processing', 'в работе'), ('processed', 'не в работе')], verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Создано', models.DateTimeField()),
                ('Изменено', models.DateTimeField()),
                ('название', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='credit',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Organization', verbose_name='Кредитная организация'),
        ),
        migrations.AddField(
            model_name='credit',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Партнёр, взявший в работу'),
        ),
    ]
